[2025-06-20T19:00:56.038+0000] {processor.py:157} INFO - Started process (PID=3143) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:00:56.038+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:00:56.040+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:00:56.039+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:00:56.044+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:00:56.042+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:00:56.044+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:00:56.057+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.021 seconds
[2025-06-20T19:01:26.872+0000] {processor.py:157} INFO - Started process (PID=3207) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:01:26.873+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:01:26.875+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:01:26.874+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:01:26.880+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:01:26.878+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:01:26.880+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:01:26.897+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.029 seconds
[2025-06-20T19:01:57.854+0000] {processor.py:157} INFO - Started process (PID=3262) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:01:57.855+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:01:57.857+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:01:57.857+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:01:57.863+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:01:57.861+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:01:57.863+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:01:57.879+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.030 seconds
[2025-06-20T19:02:28.800+0000] {processor.py:157} INFO - Started process (PID=3326) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:02:28.803+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:02:28.806+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:02:28.806+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:02:28.811+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:02:28.810+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:02:28.811+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:02:28.829+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.033 seconds
[2025-06-20T19:02:59.639+0000] {processor.py:157} INFO - Started process (PID=3390) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:02:59.640+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:02:59.643+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:02:59.643+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:02:59.647+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:02:59.646+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:02:59.648+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:02:59.666+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.031 seconds
[2025-06-20T19:03:30.589+0000] {processor.py:157} INFO - Started process (PID=3445) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:03:30.590+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:03:30.592+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:03:30.591+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:03:30.596+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:03:30.595+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:03:30.596+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:03:30.611+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.025 seconds
[2025-06-20T19:04:01.558+0000] {processor.py:157} INFO - Started process (PID=3509) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:04:01.562+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:04:01.564+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:04:01.564+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:04:01.568+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:04:01.567+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:04:01.568+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:04:01.583+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.028 seconds
[2025-06-20T19:04:32.422+0000] {processor.py:157} INFO - Started process (PID=3573) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:04:32.423+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:04:32.425+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:04:32.424+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:04:32.429+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:04:32.428+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:04:32.429+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:04:32.443+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.025 seconds
[2025-06-20T19:05:03.465+0000] {processor.py:157} INFO - Started process (PID=3628) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:05:03.468+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:05:03.472+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:05:03.471+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:05:03.477+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:05:03.476+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:05:03.477+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:05:03.495+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.035 seconds
[2025-06-20T19:05:34.355+0000] {processor.py:157} INFO - Started process (PID=3692) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:05:34.356+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:05:34.359+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:05:34.359+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:05:34.362+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:05:34.361+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:05:34.362+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:05:34.375+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.023 seconds
[2025-06-20T19:06:04.534+0000] {processor.py:157} INFO - Started process (PID=3756) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:06:04.534+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:06:04.536+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:06:04.535+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:06:04.538+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:06:04.537+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:06:04.538+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:06:04.548+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.016 seconds
[2025-06-20T19:06:35.331+0000] {processor.py:157} INFO - Started process (PID=3811) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:06:35.334+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:06:35.336+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:06:35.336+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:06:35.340+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:06:35.339+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:06:35.340+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:06:35.358+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.031 seconds
[2025-06-20T19:07:06.166+0000] {processor.py:157} INFO - Started process (PID=3875) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:07:06.169+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:07:06.173+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:07:06.172+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:07:06.177+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:07:06.176+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:07:06.177+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:07:06.193+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.032 seconds
[2025-06-20T19:07:36.966+0000] {processor.py:157} INFO - Started process (PID=3939) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:07:36.967+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:07:36.971+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:07:36.969+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:07:36.975+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:07:36.974+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:07:36.975+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:07:36.991+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.030 seconds
[2025-06-20T19:08:07.785+0000] {processor.py:157} INFO - Started process (PID=3994) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:08:07.787+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:08:07.792+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:08:07.791+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:08:07.797+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:08:07.796+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:08:07.798+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:08:07.818+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.038 seconds
[2025-06-20T19:08:38.807+0000] {processor.py:157} INFO - Started process (PID=4057) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:08:38.809+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:08:38.812+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:08:38.811+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:08:38.815+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:08:38.814+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:08:38.815+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:08:38.832+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.029 seconds
[2025-06-20T19:09:09.597+0000] {processor.py:157} INFO - Started process (PID=4121) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:09:09.600+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:09:09.603+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:09:09.602+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:09:09.608+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:09:09.607+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 7
    18:58 UTC
            ^
SyntaxError: invalid syntax
[2025-06-20T19:09:09.609+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:09:09.625+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.033 seconds
[2025-06-20T19:09:30.458+0000] {processor.py:157} INFO - Started process (PID=4176) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:09:30.460+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:09:30.462+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:09:30.462+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:09:30.470+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:09:30.531+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:09:30.530+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:09:30.540+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:09:30.539+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:09:30.550+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.096 seconds
[2025-06-20T19:09:33.493+0000] {processor.py:157} INFO - Started process (PID=4177) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:09:33.494+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:09:33.496+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:09:33.496+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:09:33.506+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:09:33.520+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:09:33.520+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:09:33.532+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:09:33.532+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:09:33.541+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.051 seconds
[2025-06-20T19:10:04.524+0000] {processor.py:157} INFO - Started process (PID=4241) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:10:04.525+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:10:04.528+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:10:04.527+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:10:04.539+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:10:04.559+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:10:04.559+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:10:04.575+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:10:04.575+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:10:04.587+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.069 seconds
[2025-06-20T19:10:34.611+0000] {processor.py:157} INFO - Started process (PID=4296) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:10:34.614+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:10:34.616+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:10:34.616+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:10:34.624+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:10:34.637+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:10:34.637+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:10:34.652+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:10:34.652+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:10:34.662+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.056 seconds
[2025-06-20T19:11:05.439+0000] {processor.py:157} INFO - Started process (PID=4360) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:11:05.442+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:11:05.443+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:11:05.443+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:11:05.450+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:11:05.510+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:11:05.510+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:11:05.519+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:11:05.519+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:11:05.528+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.092 seconds
[2025-06-20T19:11:36.489+0000] {processor.py:157} INFO - Started process (PID=4424) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:11:36.491+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:11:36.492+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:11:36.492+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:11:36.498+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:11:36.515+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:11:36.515+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:11:36.530+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:11:36.530+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:11:36.540+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.053 seconds
[2025-06-20T19:12:07.450+0000] {processor.py:157} INFO - Started process (PID=4479) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:12:07.451+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:12:07.454+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:12:07.453+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:12:07.464+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:12:07.476+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:12:07.476+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:12:07.491+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:12:07.491+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:12:07.501+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.057 seconds
[2025-06-20T19:12:38.259+0000] {processor.py:157} INFO - Started process (PID=4543) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:12:38.261+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:12:38.262+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:12:38.261+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:12:38.266+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:12:38.321+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:12:38.321+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:12:38.332+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:12:38.332+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:12:38.342+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.085 seconds
[2025-06-20T19:13:09.130+0000] {processor.py:157} INFO - Started process (PID=4607) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:13:09.132+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:13:09.135+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:13:09.134+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:13:09.145+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:13:09.164+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:13:09.164+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:13:09.181+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:13:09.181+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:13:09.192+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.066 seconds
[2025-06-20T19:13:40.058+0000] {processor.py:157} INFO - Started process (PID=4671) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:13:40.059+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:13:40.060+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:13:40.060+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:13:40.065+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:13:40.074+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:13:40.073+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:13:40.091+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:13:40.091+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:13:40.104+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.048 seconds
[2025-06-20T19:14:10.972+0000] {processor.py:157} INFO - Started process (PID=4726) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:14:10.973+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:14:10.974+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:14:10.973+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:14:10.978+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:14:11.043+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:14:11.043+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:14:11.054+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:14:11.054+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:14:11.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.093 seconds
[2025-06-20T19:14:41.869+0000] {processor.py:157} INFO - Started process (PID=4790) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:14:41.870+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:14:41.873+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:14:41.872+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:14:41.883+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:14:41.904+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:14:41.904+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:14:41.921+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:14:41.921+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:14:41.938+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.073 seconds
[2025-06-20T19:15:12.835+0000] {processor.py:157} INFO - Started process (PID=4854) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:15:12.836+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:15:12.837+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:15:12.837+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:15:12.842+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:15:12.851+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:15:12.851+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:15:12.865+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:15:12.865+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:15:12.876+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.043 seconds
[2025-06-20T19:15:14.874+0000] {processor.py:157} INFO - Started process (PID=4855) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:15:14.875+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:15:14.877+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:15:14.877+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:15:14.887+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:15:14.898+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:15:14.898+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:15:14.911+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:15:14.911+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:15:14.920+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.051 seconds
[2025-06-20T19:15:45.922+0000] {processor.py:157} INFO - Started process (PID=4910) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:15:45.923+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:15:45.925+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:15:45.925+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:15:45.932+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:15:45.996+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:15:45.996+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:15:46.006+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:15:46.005+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:15:46.014+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.096 seconds
[2025-06-20T19:16:16.104+0000] {processor.py:157} INFO - Started process (PID=4974) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:16:16.105+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:16:16.107+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:16:16.107+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:16:16.115+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:16:16.132+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:16:16.132+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:16:16.148+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:16:16.148+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:16:16.158+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.057 seconds
[2025-06-20T19:16:47.129+0000] {processor.py:157} INFO - Started process (PID=5038) to work on /opt/airflow/dags/teste.py
[2025-06-20T19:16:47.130+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T19:16:47.131+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:16:47.131+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T19:16:47.139+0000] {processor.py:836} INFO - DAG(s) dict_keys(['tutorial_taskflow_api']) retrieved from /opt/airflow/dags/teste.py
[2025-06-20T19:16:47.148+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:16:47.148+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-20T19:16:47.162+0000] {logging_mixin.py:150} INFO - [2025-06-20T19:16:47.161+0000] {dag.py:3508} INFO - Setting next_dagrun for tutorial_taskflow_api to None, run_after=None
[2025-06-20T19:16:47.175+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/teste.py took 0.049 seconds
[2025-06-20T20:48:20.122+0000] {processor.py:153} INFO - Started process (PID=71) to work on /opt/airflow/dags/teste.py
[2025-06-20T20:48:20.125+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T20:48:20.125+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:48:20.125+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T20:48:20.142+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:48:20.140+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T20:48:20.143+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T20:48:20.158+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.040 seconds
[2025-06-20T20:48:51.132+0000] {processor.py:153} INFO - Started process (PID=106) to work on /opt/airflow/dags/teste.py
[2025-06-20T20:48:51.134+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T20:48:51.135+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:48:51.135+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T20:48:51.151+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:48:51.148+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T20:48:51.151+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T20:48:51.166+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.039 seconds
[2025-06-20T20:49:21.941+0000] {processor.py:153} INFO - Started process (PID=150) to work on /opt/airflow/dags/teste.py
[2025-06-20T20:49:21.942+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T20:49:21.942+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:49:21.942+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T20:49:21.950+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:49:21.948+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T20:49:21.950+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T20:49:21.964+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.025 seconds
[2025-06-20T20:49:52.414+0000] {processor.py:153} INFO - Started process (PID=194) to work on /opt/airflow/dags/teste.py
[2025-06-20T20:49:52.415+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T20:49:52.416+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:49:52.416+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T20:49:52.425+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:49:52.423+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T20:49:52.425+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T20:49:52.439+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.026 seconds
[2025-06-20T20:50:22.885+0000] {processor.py:153} INFO - Started process (PID=229) to work on /opt/airflow/dags/teste.py
[2025-06-20T20:50:22.886+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T20:50:22.886+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:50:22.886+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T20:50:22.893+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:50:22.892+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T20:50:22.894+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T20:50:22.904+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.020 seconds
[2025-06-20T20:50:53.539+0000] {processor.py:153} INFO - Started process (PID=273) to work on /opt/airflow/dags/teste.py
[2025-06-20T20:50:53.539+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T20:50:53.540+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:50:53.540+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T20:50:53.547+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:50:53.546+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T20:50:53.547+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T20:50:53.557+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.020 seconds
[2025-06-20T20:51:23.841+0000] {processor.py:153} INFO - Started process (PID=317) to work on /opt/airflow/dags/teste.py
[2025-06-20T20:51:23.841+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T20:51:23.841+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:51:23.841+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T20:51:23.848+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:51:23.847+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T20:51:23.848+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T20:51:23.858+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.019 seconds
[2025-06-20T20:51:54.567+0000] {processor.py:153} INFO - Started process (PID=352) to work on /opt/airflow/dags/teste.py
[2025-06-20T20:51:54.568+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T20:51:54.568+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:51:54.568+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T20:51:54.576+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:51:54.574+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T20:51:54.576+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T20:51:54.586+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.021 seconds
[2025-06-20T20:52:25.269+0000] {processor.py:153} INFO - Started process (PID=396) to work on /opt/airflow/dags/teste.py
[2025-06-20T20:52:25.270+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T20:52:25.270+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:52:25.270+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T20:52:25.278+0000] {logging_mixin.py:115} INFO - [2025-06-20T20:52:25.276+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T20:52:25.278+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T20:52:25.288+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.021 seconds
[2025-06-20T21:10:11.699+0000] {processor.py:153} INFO - Started process (PID=37) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:10:11.701+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:10:11.720+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:10:11.719+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:10:11.758+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:10:11.753+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:10:11.759+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:10:11.800+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.106 seconds
[2025-06-20T21:10:42.662+0000] {processor.py:153} INFO - Started process (PID=72) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:10:42.663+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:10:42.665+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:10:42.664+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:10:42.680+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:10:42.678+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:10:42.680+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:10:42.694+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.036 seconds
[2025-06-20T21:11:15.198+0000] {processor.py:153} INFO - Started process (PID=37) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:11:15.199+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:11:15.200+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:11:15.200+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:11:15.210+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:11:15.209+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:11:15.210+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:11:15.222+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.026 seconds
[2025-06-20T21:11:46.153+0000] {processor.py:153} INFO - Started process (PID=72) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:11:46.154+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:11:46.157+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:11:46.156+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:11:46.176+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:11:46.172+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:11:46.178+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:11:46.195+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.046 seconds
[2025-06-20T21:12:16.981+0000] {processor.py:153} INFO - Started process (PID=116) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:12:16.982+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:12:16.983+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:12:16.983+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:12:16.999+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:12:16.995+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:12:16.999+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:12:17.012+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.035 seconds
[2025-06-20T21:12:47.788+0000] {processor.py:153} INFO - Started process (PID=160) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:12:47.790+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:12:47.790+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:12:47.790+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:12:47.806+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:12:47.804+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:12:47.808+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:12:47.821+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.036 seconds
[2025-06-20T21:13:18.498+0000] {processor.py:153} INFO - Started process (PID=195) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:13:18.500+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:13:18.501+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:13:18.501+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:13:18.518+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:13:18.516+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:13:18.521+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:13:18.536+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.042 seconds
[2025-06-20T21:13:49.378+0000] {processor.py:153} INFO - Started process (PID=239) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:13:49.379+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:13:49.380+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:13:49.380+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:13:49.392+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:13:49.390+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:13:49.392+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:13:49.406+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.033 seconds
[2025-06-20T21:14:20.068+0000] {processor.py:153} INFO - Started process (PID=283) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:14:20.069+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:14:20.070+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:14:20.070+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:14:20.084+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:14:20.082+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:14:20.084+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:14:20.097+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.034 seconds
[2025-06-20T21:14:50.812+0000] {processor.py:153} INFO - Started process (PID=318) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:14:50.813+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:14:50.814+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:14:50.813+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:14:50.827+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:14:50.825+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:14:50.828+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:14:50.840+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.033 seconds
[2025-06-20T21:15:21.523+0000] {processor.py:153} INFO - Started process (PID=362) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:15:21.524+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:15:21.525+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:15:21.525+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:15:21.541+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:15:21.536+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:15:21.541+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:15:21.554+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.035 seconds
[2025-06-20T21:15:52.218+0000] {processor.py:153} INFO - Started process (PID=406) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:15:52.219+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:15:52.220+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:15:52.220+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:15:52.237+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:15:52.234+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:15:52.238+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:15:52.253+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.039 seconds
[2025-06-20T21:16:23.009+0000] {processor.py:153} INFO - Started process (PID=441) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:16:23.010+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:16:23.012+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:16:23.012+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:16:23.032+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:16:23.028+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:16:23.035+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:16:23.055+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.050 seconds
[2025-06-20T21:16:36.633+0000] {processor.py:153} INFO - Started process (PID=36) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:16:36.633+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:16:36.635+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:16:36.635+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:16:36.644+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:16:36.643+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:16:36.645+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:16:36.656+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.025 seconds
[2025-06-20T21:17:07.602+0000] {processor.py:153} INFO - Started process (PID=71) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:17:07.606+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:17:07.607+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:17:07.606+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:17:07.621+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:17:07.619+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:17:07.621+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:17:07.635+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.037 seconds
[2025-06-20T21:17:38.408+0000] {processor.py:153} INFO - Started process (PID=115) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:17:38.409+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:17:38.409+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:17:38.409+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:17:38.428+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:17:38.424+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:17:38.431+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:17:38.447+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.043 seconds
[2025-06-20T21:18:09.354+0000] {processor.py:153} INFO - Started process (PID=159) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:18:09.356+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:18:09.357+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:18:09.357+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:18:09.370+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:18:09.368+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:18:09.370+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:18:09.386+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.036 seconds
[2025-06-20T21:18:40.106+0000] {processor.py:153} INFO - Started process (PID=194) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:18:40.108+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:18:40.108+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:18:40.108+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:18:40.123+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:18:40.121+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:18:40.123+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:18:40.139+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.037 seconds
[2025-06-20T21:19:10.811+0000] {processor.py:153} INFO - Started process (PID=238) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:19:10.813+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:19:10.814+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:19:10.814+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:19:10.829+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:19:10.828+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:19:10.830+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:19:10.842+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.035 seconds
[2025-06-20T21:50:09.288+0000] {processor.py:153} INFO - Started process (PID=37) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:50:09.294+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:50:09.295+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:50:09.295+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:50:09.319+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:50:09.318+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:50:09.320+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:50:09.343+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.059 seconds
[2025-06-20T21:50:40.314+0000] {processor.py:153} INFO - Started process (PID=72) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:50:40.317+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:50:40.318+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:50:40.318+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:50:40.340+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:50:40.337+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:50:40.342+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:50:40.359+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.051 seconds
[2025-06-20T21:51:10.461+0000] {processor.py:153} INFO - Started process (PID=116) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:51:10.462+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:51:10.463+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:51:10.463+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:51:10.484+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:51:10.480+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:51:10.484+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:51:10.502+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.045 seconds
[2025-06-20T21:51:40.654+0000] {processor.py:153} INFO - Started process (PID=160) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:51:40.655+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:51:40.657+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:51:40.656+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:51:40.671+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:51:40.669+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:51:40.671+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:51:40.687+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.036 seconds
[2025-06-20T21:52:10.863+0000] {processor.py:153} INFO - Started process (PID=195) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:52:10.867+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:52:10.868+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:52:10.868+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:52:10.882+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:52:10.881+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:52:10.883+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:52:10.901+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.042 seconds
[2025-06-20T21:52:41.716+0000] {processor.py:153} INFO - Started process (PID=239) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:52:41.719+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:52:41.720+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:52:41.720+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:52:41.741+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:52:41.739+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:52:41.742+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:52:41.757+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.046 seconds
[2025-06-20T21:53:12.710+0000] {processor.py:153} INFO - Started process (PID=283) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:53:12.712+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:53:12.715+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:53:12.715+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:53:12.732+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:53:12.730+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:53:12.733+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:53:12.748+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.042 seconds
[2025-06-20T21:53:43.686+0000] {processor.py:153} INFO - Started process (PID=318) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:53:43.687+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:53:43.688+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:53:43.688+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:53:43.707+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:53:43.702+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:53:43.707+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:53:43.722+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.040 seconds
[2025-06-20T21:54:14.703+0000] {processor.py:153} INFO - Started process (PID=362) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:54:14.704+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:54:14.705+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:54:14.705+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:54:14.723+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:54:14.720+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:54:14.726+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:54:14.738+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.039 seconds
[2025-06-20T21:54:45.587+0000] {processor.py:153} INFO - Started process (PID=406) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:54:45.590+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:54:45.591+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:54:45.591+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:54:45.606+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:54:45.604+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:54:45.606+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:54:45.619+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.036 seconds
[2025-06-20T21:55:16.585+0000] {processor.py:153} INFO - Started process (PID=441) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:55:16.587+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:55:16.588+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:55:16.588+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:55:16.610+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:55:16.605+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:55:16.613+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:55:16.626+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.045 seconds
[2025-06-20T21:55:46.672+0000] {processor.py:153} INFO - Started process (PID=485) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:55:46.674+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:55:46.675+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:55:46.675+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:55:46.704+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:55:46.701+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:55:46.704+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:55:46.721+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.059 seconds
[2025-06-20T21:56:16.762+0000] {processor.py:153} INFO - Started process (PID=529) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:56:16.764+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:56:16.764+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:56:16.764+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:56:16.779+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:56:16.777+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:56:16.780+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:56:16.796+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.038 seconds
[2025-06-20T21:56:46.886+0000] {processor.py:153} INFO - Started process (PID=564) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:56:46.887+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:56:46.888+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:56:46.888+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:56:46.904+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:56:46.902+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:56:46.904+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:56:46.918+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.038 seconds
[2025-06-20T21:57:17.896+0000] {processor.py:153} INFO - Started process (PID=608) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:57:17.897+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:57:17.898+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:57:17.898+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:57:17.910+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:57:17.908+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:57:17.910+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:57:17.926+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.033 seconds
[2025-06-20T21:57:48.107+0000] {processor.py:153} INFO - Started process (PID=652) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:57:48.111+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:57:48.112+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:57:48.111+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:57:48.129+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:57:48.127+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:57:48.130+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:57:48.143+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.041 seconds
[2025-06-20T21:58:18.200+0000] {processor.py:153} INFO - Started process (PID=687) to work on /opt/airflow/dags/teste.py
[2025-06-20T21:58:18.202+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/teste.py for tasks to queue
[2025-06-20T21:58:18.203+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:58:18.203+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/teste.py
[2025-06-20T21:58:18.220+0000] {logging_mixin.py:115} INFO - [2025-06-20T21:58:18.217+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/teste.py", line 37, in <module>
    tags=["teste"],
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2997, in wrapper
    dag_bound_args = dag_sig.bind_partial(*dag_args, **dag_kwargs)
  File "/usr/local/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/usr/local/lib/python3.7/inspect.py", line 3006, in _bind
    arg=next(iter(kwargs))))
TypeError: got an unexpected keyword argument 'schedule'
[2025-06-20T21:58:18.220+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/teste.py
[2025-06-20T21:58:18.240+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/teste.py took 0.043 seconds
